#+TITLE:
#+OPTIONS: toc:nil author:nil date:nil

* company-org-headings

- ~company-org-headings~ provides prefix completion using ~string-prefix-p~ by all words in the org headings. A real fuzzy matching is not planned for this ~company-backend~.
- To improve the performance of candidates retrieval and the meaningfulness of candidates, ~company-org-headings~ removes stop words (most common words in a language) from the candidates. you may extend the ~company-org-headings/stopwords~ to your needs.
- Specify the directory to retrieve the org headings from in ~company-org-headings/search-directory~.
- Setting ~company-org-headings/restricted-to-directory~ to ~t~ will restrict the ~company-backend~ to the given directory. This makes sense if you only want the completion in a directory dedicated to notes files rather than in all ~org-mode~ buffers.
- Depending on the number of files that reside in the ~company-org-headings/search-directory~, the speed of candidates retrieval can be improved significantly by setting ~company-org-headings/no-cache~ to ~nil~ and ~company-org-headings/case-sensitive~ to ~t~ (default).
- Short headings like "Summary" tend to omit contextual information, the heading text and the filename alone may not be satisfactory. A non-nil ~company-org-headings/show-headings-context~ will reveal the higher level heading to show the context of the candidate at point in the minibuffer.
